[['Cannabis', 'Weed'], '/products/all/Weed']
(['Cannabis', 'Weed'], '/products/all/Weed/2')
(['Cannabis', 'Weed'], '/products/all/Weed/3')
(['Cannabis', 'Weed'], '/products/all/Weed/4')
(['Cannabis', 'Weed'], '/products/all/Weed/5')
(['Cannabis', 'Weed'], '/products/all/Weed/6')
(['Cannabis', 'Weed'], '/products/all/Weed/7')
(['Cannabis', 'Weed'], '/products/all/Weed/8')
(['Cannabis', 'Weed'], '/products/all/Weed/9')
(['Cannabis', 'Weed'], '/products/all/Weed/10')
(['Cannabis', 'Weed'], '/products/all/Weed/11')
(['Cannabis', 'Weed'], '/products/all/Weed/12')
(['Cannabis', 'Weed'], '/products/all/Weed/13')
(['Cannabis', 'Weed'], '/products/all/Weed/14')
(['Cannabis', 'Weed'], '/products/all/Weed/15')
(['Cannabis', 'Weed'], '/products/all/Weed/16')
(['Cannabis', 'Weed'], '/products/all/Weed/17')
(['Cannabis', 'Weed'], '/products/all/Weed/18')
(['Cannabis', 'Weed'], '/products/all/Weed/19')
(['Cannabis', 'Weed'], '/products/all/Weed/20')
(['Cannabis', 'Weed'], '/products/all/Weed/21')
(['Cannabis', 'Weed'], '/products/all/Weed/22')
(['Cannabis', 'Weed'], '/products/all/Weed/23')
(['Cannabis', 'Weed'], '/products/all/Weed/24')
(['Cannabis', 'Weed'], '/products/all/Weed/25')
(['Cannabis', 'Weed'], '/products/all/Weed/26')
(['Cannabis', 'Weed'], '/products/all/Weed/27')
(['Cannabis', 'Weed'], '/products/all/Weed/28')
(['Cannabis', 'Weed'], '/products/all/Weed/29')
(['Cannabis', 'Weed'], '/products/all/Weed/30')
(['Cannabis', 'Weed'], '/products/all/Weed/31')
(['Cannabis', 'Weed'], '/products/all/Weed/32')
(['Cannabis', 'Weed'], '/products/all/Weed/33')
(['Cannabis', 'Weed'], '/products/all/Weed/34')
(['Cannabis', 'Weed'], '/products/all/Weed/35')
(['Cannabis', 'Weed'], '/products/all/Weed/36')
(['Cannabis', 'Weed'], '/products/all/Weed/37')
(['Cannabis', 'Weed'], '/products/all/Weed/38')
(['Cannabis', 'Weed'], '/products/all/Weed/39')
(['Cannabis', 'Weed'], '/products/all/Weed/40')
(['Cannabis', 'Weed'], '/products/all/Weed/41')
(['Cannabis', 'Weed'], '/products/all/Weed/42')
(['Cannabis', 'Weed'], '/products/all/Weed/43')
(['Cannabis', 'Weed'], '/products/all/Weed/44')
(['Cannabis', 'Weed'], '/products/all/Weed/45')
(['Cannabis', 'Weed'], '/products/all/Weed/46')
(['Cannabis', 'Weed'], '/products/all/Weed/47')
(['Cannabis', 'Weed'], '/products/all/Weed/48')
(['Cannabis', 'Weed'], '/products/all/Weed/49')
(['Cannabis', 'Weed'], '/products/all/Weed/50')
(['Cannabis', 'Weed'], '/products/all/Weed/51')
(['Cannabis', 'Weed'], '/products/all/Weed/52')
(['Cannabis', 'Weed'], '/products/all/Weed/53')
(['Cannabis', 'Weed'], '/products/all/Weed/54')
(['Cannabis', 'Weed'], '/products/all/Weed/55')
(['Cannabis', 'Weed'], '/products/all/Weed/56')
(['Cannabis', 'Weed'], '/products/all/Weed/57')
(['Cannabis', 'Weed'], '/products/all/Weed/58')
(['Cannabis', 'Weed'], '/products/all/Weed/59')
(['Cannabis', 'Weed'], '/products/all/Weed/60')
(['Cannabis', 'Weed'], '/products/all/Weed/61')
(['Cannabis', 'Weed'], '/products/all/Weed/62')
(['Cannabis', 'Weed'], '/products/all/Weed/63')
(['Cannabis', 'Weed'], '/products/all/Weed/64')
(['Cannabis', 'Weed'], '/products/all/Weed/65')
(['Cannabis', 'Weed'], '/products/all/Weed/66')
(['Cannabis', 'Weed'], '/products/all/Weed/67')
(['Cannabis', 'Weed'], '/products/all/Weed/68')
(['Cannabis', 'Weed'], '/products/all/Weed/69')
(['Cannabis', 'Weed'], '/products/all/Weed/70')
(['Cannabis', 'Weed'], '/products/all/Weed/71')
(['Cannabis', 'Weed'], '/products/all/Weed/72')
(['Cannabis', 'Weed'], '/products/all/Weed/73')
(['Cannabis', 'Weed'], '/products/all/Weed/74')
(['Cannabis', 'Weed'], '/products/all/Weed/75')
(['Cannabis', 'Weed'], '/products/all/Weed/76')
(['Cannabis', 'Weed'], '/products/all/Weed/77')
(['Cannabis', 'Weed'], '/products/all/Weed/78')
(['Cannabis', 'Weed'], '/products/all/Weed/79')
(['Cannabis', 'Weed'], '/products/all/Weed/80')
(['Cannabis', 'Weed'], '/products/all/Weed/81')
(['Cannabis', 'Weed'], '/products/all/Weed/82')
(['Cannabis', 'Weed'], '/products/all/Weed/83')
(['Cannabis', 'Weed'], '/products/all/Weed/84')
(['Cannabis', 'Weed'], '/products/all/Weed/85')
(['Cannabis', 'Weed'], '/products/all/Weed/86')
(['Cannabis', 'Weed'], '/products/all/Weed/87')
(['Cannabis', 'Weed'], '/products/all/Weed/88')
(['Cannabis', 'Weed'], '/products/all/Weed/89')
(['Cannabis', 'Weed'], '/products/all/Weed/90')
(['Cannabis', 'Weed'], '/products/all/Weed/91')
(['Cannabis', 'Weed'], '/products/all/Weed/92')
(['Cannabis', 'Weed'], '/products/all/Weed/93')
(['Cannabis', 'Weed'], '/products/all/Weed/94')
(['Cannabis', 'Weed'], '/products/all/Weed/95')
(['Cannabis', 'Weed'], '/products/all/Weed/96')
(['Cannabis', 'Weed'], '/products/all/Weed/97')
(['Cannabis', 'Weed'], '/products/all/Weed/98')
(['Cannabis', 'Weed'], '/products/all/Weed/99')
(['Cannabis', 'Weed'], '/products/all/Weed/100')
(['Cannabis', 'Weed'], '/products/all/Weed/101')
(['Cannabis', 'Weed'], '/products/all/Weed/102')
(['Cannabis', 'Weed'], '/products/all/Weed/103')
(['Cannabis', 'Weed'], '/products/all/Weed/104')
(['Cannabis', 'Weed'], '/products/all/Weed/105')
(['Cannabis', 'Weed'], '/products/all/Weed/106')
(['Cannabis', 'Weed'], '/products/all/Weed/107')
(['Cannabis', 'Weed'], '/products/all/Weed/108')
(['Cannabis', 'Weed'], '/products/all/Weed/109')
(['Cannabis', 'Weed'], '/products/all/Weed/110')
(['Cannabis', 'Weed'], '/products/all/Weed/111')
(['Cannabis', 'Weed'], '/products/all/Weed/112')
[['Cannabis', 'Hashish'], '/products/all/Hashish']
(['Cannabis', 'Hashish'], '/products/all/Hashish/2')
(['Cannabis', 'Hashish'], '/products/all/Hashish/3')
(['Cannabis', 'Hashish'], '/products/all/Hashish/4')
(['Cannabis', 'Hashish'], '/products/all/Hashish/5')
(['Cannabis', 'Hashish'], '/products/all/Hashish/6')
(['Cannabis', 'Hashish'], '/products/all/Hashish/7')
(['Cannabis', 'Hashish'], '/products/all/Hashish/8')
(['Cannabis', 'Hashish'], '/products/all/Hashish/9')
(['Cannabis', 'Hashish'], '/products/all/Hashish/10')
(['Cannabis', 'Hashish'], '/products/all/Hashish/11')
(['Cannabis', 'Hashish'], '/products/all/Hashish/12')
(['Cannabis', 'Hashish'], '/products/all/Hashish/13')
(['Cannabis', 'Hashish'], '/products/all/Hashish/14')
(['Cannabis', 'Hashish'], '/products/all/Hashish/15')
(['Cannabis', 'Hashish'], '/products/all/Hashish/16')
(['Cannabis', 'Hashish'], '/products/all/Hashish/17')
(['Cannabis', 'Hashish'], '/products/all/Hashish/18')
(['Cannabis', 'Hashish'], '/products/all/Hashish/19')
(['Cannabis', 'Hashish'], '/products/all/Hashish/20')
(['Cannabis', 'Hashish'], '/products/all/Hashish/21')
(['Cannabis', 'Hashish'], '/products/all/Hashish/22')
(['Cannabis', 'Hashish'], '/products/all/Hashish/23')
[['Cannabis', 'Edibles'], '/products/all/Edibles']
(['Cannabis', 'Edibles'], '/products/all/Edibles/2')
(['Cannabis', 'Edibles'], '/products/all/Edibles/3')
(['Cannabis', 'Edibles'], '/products/all/Edibles/4')
(['Cannabis', 'Edibles'], '/products/all/Edibles/5')
(['Cannabis', 'Edibles'], '/products/all/Edibles/6')
(['Cannabis', 'Edibles'], '/products/all/Edibles/7')
(['Cannabis', 'Edibles'], '/products/all/Edibles/8')
(['Cannabis', 'Edibles'], '/products/all/Edibles/9')
(['Cannabis', 'Edibles'], '/products/all/Edibles/10')
[['Cannabis', 'Concentrate'], '/products/all/Concentrate']
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/2')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/3')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/4')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/5')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/6')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/7')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/8')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/9')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/10')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/11')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/12')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/13')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/14')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/15')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/16')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/17')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/18')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/19')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/20')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/21')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/22')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/23')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/24')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/25')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/26')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/27')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/28')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/29')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/30')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/31')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/32')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/33')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/34')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/35')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/36')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/37')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/38')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/39')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/40')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/41')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/42')
(['Cannabis', 'Concentrate'], '/products/all/Concentrate/43')
[['Cannabis', 'Synthetics'], '/products/all/Synthetics']
(['Cannabis', 'Synthetics'], '/products/all/Synthetics/2')
(['Cannabis', 'Synthetics'], '/products/all/Synthetics/3')
[['Cannabis', 'Seeds and Clones'], '/products/all/Seeds+and+Clones']
(['Cannabis', 'Seeds and Clones'], '/products/all/Seeds+and+Clones/2')
[['Stimulants', 'Cocaine'], '/products/all/Cocaine']
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/2')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/3')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/4')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/5')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/6')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/7')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/8')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/9')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/10')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/11')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/12')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/13')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/14')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/15')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/16')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/17')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/18')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/19')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/20')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/21')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/22')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/23')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/24')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/25')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/26')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/27')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/28')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/29')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/30')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/31')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/32')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/33')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/34')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/35')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/36')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/37')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/38')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/39')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/40')
(['Stimulants', 'Cocaine'], '/products/all/Cocaine/41')
[['Stimulants', 'Crack'], '/products/all/Crack']
(['Stimulants', 'Crack'], '/products/all/Crack/2')
(['Stimulants', 'Crack'], '/products/all/Crack/3')
(['Stimulants', 'Crack'], '/products/all/Crack/4')
[['Stimulants', 'Amphetamine'], '/products/all/Amphetamine']
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/2')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/3')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/4')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/5')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/6')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/7')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/8')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/9')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/10')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/11')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/12')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/13')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/14')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/15')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/16')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/17')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/18')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/19')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/20')
(['Stimulants', 'Amphetamine'], '/products/all/Amphetamine/21')
[['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine']
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/2')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/3')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/4')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/5')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/6')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/7')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/8')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/9')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/10')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/11')
(['Stimulants', 'Methamphetamine'], '/products/all/Methamphetamine/12')
[['Stimulants', 'A-PVP'], '/products/all/A%2DPVP']
[['Stimulants', 'Cathinones'], '/products/all/Cathinones']
[['Stimulants', 'Snuff'], '/products/all/Snuff']
[['Stimulants', 'MDPV'], '/products/all/MDPV']
[['Stimulants', 'Nicotine'], '/products/all/Nicotine']
(['Stimulants', 'Nicotine'], '/products/all/Nicotine/2')
(['Stimulants', 'Nicotine'], '/products/all/Nicotine/3')
(['Stimulants', 'Nicotine'], '/products/all/Nicotine/4')
[['Stimulants', '2-FMA 4-FA'], '/products/all/2%2DFMA+4%2DFA']
[['Stimulants', 'Phenidades'], '/products/all/Phenidades']
[['Narcotics', 'Heroin'], '/products/all/Heroin']
(['Narcotics', 'Heroin'], '/products/all/Heroin/2')
(['Narcotics', 'Heroin'], '/products/all/Heroin/3')
(['Narcotics', 'Heroin'], '/products/all/Heroin/4')
(['Narcotics', 'Heroin'], '/products/all/Heroin/5')
(['Narcotics', 'Heroin'], '/products/all/Heroin/6')
(['Narcotics', 'Heroin'], '/products/all/Heroin/7')
(['Narcotics', 'Heroin'], '/products/all/Heroin/8')
(['Narcotics', 'Heroin'], '/products/all/Heroin/9')
(['Narcotics', 'Heroin'], '/products/all/Heroin/10')
(['Narcotics', 'Heroin'], '/products/all/Heroin/11')
(['Narcotics', 'Heroin'], '/products/all/Heroin/12')
(['Narcotics', 'Heroin'], '/products/all/Heroin/13')
(['Narcotics', 'Heroin'], '/products/all/Heroin/14')
(['Narcotics', 'Heroin'], '/products/all/Heroin/15')
(['Narcotics', 'Heroin'], '/products/all/Heroin/16')
(['Narcotics', 'Heroin'], '/products/all/Heroin/17')
[['Narcotics', 'Oxycodone'], '/products/all/Oxycodone']
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/2')
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/3')
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/4')
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/5')
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/6')
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/7')
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/8')
(['Narcotics', 'Oxycodone'], '/products/all/Oxycodone/9')
[['Narcotics', 'Buprenorphine'], '/products/all/Buprenorphine']
(['Narcotics', 'Buprenorphine'], '/products/all/Buprenorphine/2')
[['Narcotics', 'Tramadol'], '/products/all/Tramadol']
(['Narcotics', 'Tramadol'], '/products/all/Tramadol/2')
(['Narcotics', 'Tramadol'], '/products/all/Tramadol/3')
[['Narcotics', 'Codeine'], '/products/all/Codeine']
(['Narcotics', 'Codeine'], '/products/all/Codeine/2')
(['Narcotics', 'Codeine'], '/products/all/Codeine/3')
(['Narcotics', 'Codeine'], '/products/all/Codeine/4')
[['Narcotics', 'Morphine'], '/products/all/Morphine']
(['Narcotics', 'Morphine'], '/products/all/Morphine/2')
[['Narcotics', 'Opium'], '/products/all/Opium']
(['Narcotics', 'Opium'], '/products/all/Opium/2')
[['Narcotics', 'Metadon'], '/products/all/Metadon']
[['Narcotics', 'Other Narcotics'], '/products/all/Other+Narcotics']
(['Narcotics', 'Other Narcotics'], '/products/all/Other+Narcotics/2')
(['Narcotics', 'Other Narcotics'], '/products/all/Other+Narcotics/3')
(['Narcotics', 'Other Narcotics'], '/products/all/Other+Narcotics/4')
[['Empathogens', 'MDMA'], '/products/all/MDMA']
(['Empathogens', 'MDMA'], '/products/all/MDMA/2')
(['Empathogens', 'MDMA'], '/products/all/MDMA/3')
(['Empathogens', 'MDMA'], '/products/all/MDMA/4')
(['Empathogens', 'MDMA'], '/products/all/MDMA/5')
(['Empathogens', 'MDMA'], '/products/all/MDMA/6')
(['Empathogens', 'MDMA'], '/products/all/MDMA/7')
(['Empathogens', 'MDMA'], '/products/all/MDMA/8')
(['Empathogens', 'MDMA'], '/products/all/MDMA/9')
(['Empathogens', 'MDMA'], '/products/all/MDMA/10')
(['Empathogens', 'MDMA'], '/products/all/MDMA/11')
(['Empathogens', 'MDMA'], '/products/all/MDMA/12')
(['Empathogens', 'MDMA'], '/products/all/MDMA/13')
(['Empathogens', 'MDMA'], '/products/all/MDMA/14')
(['Empathogens', 'MDMA'], '/products/all/MDMA/15')
(['Empathogens', 'MDMA'], '/products/all/MDMA/16')
(['Empathogens', 'MDMA'], '/products/all/MDMA/17')
(['Empathogens', 'MDMA'], '/products/all/MDMA/18')
(['Empathogens', 'MDMA'], '/products/all/MDMA/19')
(['Empathogens', 'MDMA'], '/products/all/MDMA/20')
(['Empathogens', 'MDMA'], '/products/all/MDMA/21')
(['Empathogens', 'MDMA'], '/products/all/MDMA/22')
(['Empathogens', 'MDMA'], '/products/all/MDMA/23')
(['Empathogens', 'MDMA'], '/products/all/MDMA/24')
(['Empathogens', 'MDMA'], '/products/all/MDMA/25')
(['Empathogens', 'MDMA'], '/products/all/MDMA/26')
(['Empathogens', 'MDMA'], '/products/all/MDMA/27')
(['Empathogens', 'MDMA'], '/products/all/MDMA/28')
[['Empathogens', 'Ecstacy'], '/products/all/Ecstacy']
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/2')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/3')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/4')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/5')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/6')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/7')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/8')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/9')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/10')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/11')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/12')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/13')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/14')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/15')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/16')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/17')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/18')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/19')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/20')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/21')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/22')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/23')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/24')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/25')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/26')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/27')
(['Empathogens', 'Ecstacy'], '/products/all/Ecstacy/28')
[['Empathogens', 'MDA MDAI'], '/products/all/MDA+MDAI']
[['Empathogens', 'Methylone'], '/products/all/Methylone']
[['Psychedelics', 'LSD'], '/products/all/LSD']
(['Psychedelics', 'LSD'], '/products/all/LSD/2')
(['Psychedelics', 'LSD'], '/products/all/LSD/3')
(['Psychedelics', 'LSD'], '/products/all/LSD/4')
(['Psychedelics', 'LSD'], '/products/all/LSD/5')
(['Psychedelics', 'LSD'], '/products/all/LSD/6')
(['Psychedelics', 'LSD'], '/products/all/LSD/7')
(['Psychedelics', 'LSD'], '/products/all/LSD/8')
(['Psychedelics', 'LSD'], '/products/all/LSD/9')
(['Psychedelics', 'LSD'], '/products/all/LSD/10')
(['Psychedelics', 'LSD'], '/products/all/LSD/11')
(['Psychedelics', 'LSD'], '/products/all/LSD/12')
(['Psychedelics', 'LSD'], '/products/all/LSD/13')
(['Psychedelics', 'LSD'], '/products/all/LSD/14')
(['Psychedelics', 'LSD'], '/products/all/LSD/15')
(['Psychedelics', 'LSD'], '/products/all/LSD/16')
(['Psychedelics', 'LSD'], '/products/all/LSD/17')
(['Psychedelics', 'LSD'], '/products/all/LSD/18')
(['Psychedelics', 'LSD'], '/products/all/LSD/19')
(['Psychedelics', 'LSD'], '/products/all/LSD/20')
[['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT']
(['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT/2')
(['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT/3')
(['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT/4')
(['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT/5')
(['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT/6')
(['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT/7')
(['Psychedelics', 'DMT AMT'], '/products/all/DMT+AMT/8')
[['Psychedelics', 'Mushrooms'], '/products/all/Mushrooms']
(['Psychedelics', 'Mushrooms'], '/products/all/Mushrooms/2')
(['Psychedelics', 'Mushrooms'], '/products/all/Mushrooms/3')
(['Psychedelics', 'Mushrooms'], '/products/all/Mushrooms/4')
(['Psychedelics', 'Mushrooms'], '/products/all/Mushrooms/5')
(['Psychedelics', 'Mushrooms'], '/products/all/Mushrooms/6')
(['Psychedelics', 'Mushrooms'], '/products/all/Mushrooms/7')
[['Psychedelics', '25x-NBOMe'], '/products/all/25x%2DNBOMe']
[['Psychedelics', 'Mescaline'], '/products/all/Mescaline']
[['Psychedelics', 'Ayahuasca'], '/products/all/Ayahuasca']
[['Psychedelics', '2C-x'], '/products/all/2C%2Dx']
(['Psychedelics', '2C-x'], '/products/all/2C%2Dx/2')
(['Psychedelics', '2C-x'], '/products/all/2C%2Dx/3')
(['Psychedelics', '2C-x'], '/products/all/2C%2Dx/4')
(['Psychedelics', '2C-x'], '/products/all/2C%2Dx/5')
[['Psychedelics', '5-MeO-DiPT'], '/products/all/5%2DMeO%2DDiPT']
[['Psychedelics', '5-MeO-MiPT'], '/products/all/5%2DMeO%2DMiPT']
[['Psychedelics', 'LSA LSZ'], '/products/all/LSA+LSZ']
[['Psychedelics', 'AL-LAD'], '/products/all/AL%2DLAD']
[['Psychedelics', 'Ibogaine'], '/products/all/Ibogaine']
[['Psychedelics', 'DOx'], '/products/all/DOx']
[['Pharma', 'Benzos'], '/products/all/Benzos']
(['Pharma', 'Benzos'], '/products/all/Benzos/2')
(['Pharma', 'Benzos'], '/products/all/Benzos/3')
(['Pharma', 'Benzos'], '/products/all/Benzos/4')
(['Pharma', 'Benzos'], '/products/all/Benzos/5')
(['Pharma', 'Benzos'], '/products/all/Benzos/6')
(['Pharma', 'Benzos'], '/products/all/Benzos/7')
(['Pharma', 'Benzos'], '/products/all/Benzos/8')
(['Pharma', 'Benzos'], '/products/all/Benzos/9')
(['Pharma', 'Benzos'], '/products/all/Benzos/10')
(['Pharma', 'Benzos'], '/products/all/Benzos/11')
(['Pharma', 'Benzos'], '/products/all/Benzos/12')
(['Pharma', 'Benzos'], '/products/all/Benzos/13')
(['Pharma', 'Benzos'], '/products/all/Benzos/14')
(['Pharma', 'Benzos'], '/products/all/Benzos/15')
(['Pharma', 'Benzos'], '/products/all/Benzos/16')
(['Pharma', 'Benzos'], '/products/all/Benzos/17')
(['Pharma', 'Benzos'], '/products/all/Benzos/18')
(['Pharma', 'Benzos'], '/products/all/Benzos/19')
(['Pharma', 'Benzos'], '/products/all/Benzos/20')
(['Pharma', 'Benzos'], '/products/all/Benzos/21')
(['Pharma', 'Benzos'], '/products/all/Benzos/22')
(['Pharma', 'Benzos'], '/products/all/Benzos/23')
(['Pharma', 'Benzos'], '/products/all/Benzos/24')
(['Pharma', 'Benzos'], '/products/all/Benzos/25')
(['Pharma', 'Benzos'], '/products/all/Benzos/26')
(['Pharma', 'Benzos'], '/products/all/Benzos/27')
(['Pharma', 'Benzos'], '/products/all/Benzos/28')
(['Pharma', 'Benzos'], '/products/all/Benzos/29')
(['Pharma', 'Benzos'], '/products/all/Benzos/30')
(['Pharma', 'Benzos'], '/products/all/Benzos/31')
(['Pharma', 'Benzos'], '/products/all/Benzos/32')
(['Pharma', 'Benzos'], '/products/all/Benzos/33')
(['Pharma', 'Benzos'], '/products/all/Benzos/34')
(['Pharma', 'Benzos'], '/products/all/Benzos/35')
(['Pharma', 'Benzos'], '/products/all/Benzos/36')
[['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds']
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/2')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/3')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/4')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/5')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/6')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/7')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/8')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/9')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/10')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/11')
(['Pharma', 'ED Sex Meds'], '/products/all/ED+Sex+Meds/12')
[['Pharma', 'Sleep Aids'], '/products/all/Sleep+Aids']
(['Pharma', 'Sleep Aids'], '/products/all/Sleep+Aids/2')
(['Pharma', 'Sleep Aids'], '/products/all/Sleep+Aids/3')
(['Pharma', 'Sleep Aids'], '/products/all/Sleep+Aids/4')
[['Pharma', 'ADHD'], '/products/all/ADHD']
(['Pharma', 'ADHD'], '/products/all/ADHD/2')
(['Pharma', 'ADHD'], '/products/all/ADHD/3')
(['Pharma', 'ADHD'], '/products/all/ADHD/4')
(['Pharma', 'ADHD'], '/products/all/ADHD/5')
[['Pharma', 'Pain Medication'], '/products/all/Pain+Medication']
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/2')
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/3')
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/4')
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/5')
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/6')
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/7')
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/8')
(['Pharma', 'Pain Medication'], '/products/all/Pain+Medication/9')
[['Pharma', 'Sedatives'], '/products/all/Sedatives']
(['Pharma', 'Sedatives'], '/products/all/Sedatives/2')
[['Pharma', 'Muscle Relaxers'], '/products/all/Muscle+Relaxers']
[['Pharma', 'MAOIs'], '/products/all/MAOIs']
[['Pharma', 'Nootropics'], '/products/all/Nootropics']
(['Pharma', 'Nootropics'], '/products/all/Nootropics/2')
(['Pharma', 'Nootropics'], '/products/all/Nootropics/3')
(['Pharma', 'Nootropics'], '/products/all/Nootropics/4')
[['Pharma', 'Other Pharma'], '/products/all/Other+Pharma']
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/2')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/3')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/4')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/5')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/6')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/7')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/8')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/9')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/10')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/11')
(['Pharma', 'Other Pharma'], '/products/all/Other+Pharma/12')
[['Dissociatives', 'Ketamine'], '/products/all/Ketamine']
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/2')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/3')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/4')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/5')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/6')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/7')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/8')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/9')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/10')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/11')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/12')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/13')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/14')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/15')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/16')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/17')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/18')
(['Dissociatives', 'Ketamine'], '/products/all/Ketamine/19')
[['Dissociatives', 'Salvia'], '/products/all/Salvia']
[['Dissociatives', 'MXE MXP'], '/products/all/MXE+MXP']
[['Depressants', 'Alcohol'], '/products/all/Alcohol']
[['Depressants', 'GHB GBL'], '/products/all/GHB+GBL']
(['Depressants', 'GHB GBL'], '/products/all/GHB+GBL/2')
(['Depressants', 'GHB GBL'], '/products/all/GHB+GBL/3')
(['Depressants', 'GHB GBL'], '/products/all/GHB+GBL/4')
(['Depressants', 'GHB GBL'], '/products/all/GHB+GBL/5')
[['Other', 'Paraphernalia'], '/products/all/Paraphernalia']
(['Other', 'Paraphernalia'], '/products/all/Paraphernalia/2')
[['Other', 'Body Building'], '/products/all/Body+Building']
(['Other', 'Body Building'], '/products/all/Body+Building/2')
(['Other', 'Body Building'], '/products/all/Body+Building/3')
(['Other', 'Body Building'], '/products/all/Body+Building/4')
(['Other', 'Body Building'], '/products/all/Body+Building/5')
(['Other', 'Body Building'], '/products/all/Body+Building/6')
(['Other', 'Body Building'], '/products/all/Body+Building/7')
(['Other', 'Body Building'], '/products/all/Body+Building/8')
(['Other', 'Body Building'], '/products/all/Body+Building/9')
(['Other', 'Body Building'], '/products/all/Body+Building/10')
(['Other', 'Body Building'], '/products/all/Body+Building/11')
(['Other', 'Body Building'], '/products/all/Body+Building/12')
(['Other', 'Body Building'], '/products/all/Body+Building/13')
(['Other', 'Body Building'], '/products/all/Body+Building/14')
(['Other', 'Body Building'], '/products/all/Body+Building/15')
(['Other', 'Body Building'], '/products/all/Body+Building/16')
(['Other', 'Body Building'], '/products/all/Body+Building/17')
(['Other', 'Body Building'], '/products/all/Body+Building/18')
(['Other', 'Body Building'], '/products/all/Body+Building/19')
(['Other', 'Body Building'], '/products/all/Body+Building/20')
(['Other', 'Body Building'], '/products/all/Body+Building/21')
(['Other', 'Body Building'], '/products/all/Body+Building/22')
(['Other', 'Body Building'], '/products/all/Body+Building/23')
(['Other', 'Body Building'], '/products/all/Body+Building/24')
(['Other', 'Body Building'], '/products/all/Body+Building/25')
(['Other', 'Body Building'], '/products/all/Body+Building/26')
(['Other', 'Body Building'], '/products/all/Body+Building/27')
(['Other', 'Body Building'], '/products/all/Body+Building/28')
(['Other', 'Body Building'], '/products/all/Body+Building/29')
(['Other', 'Body Building'], '/products/all/Body+Building/30')
(['Other', 'Body Building'], '/products/all/Body+Building/31')
(['Other', 'Body Building'], '/products/all/Body+Building/32')
[['Other', 'Drug Production'], '/products/all/Drug+Production']
(['Other', 'Drug Production'], '/products/all/Drug+Production/2')
[['Other', 'Digital Items'], '/products/all/Digital+Items']
(['Other', 'Digital Items'], '/products/all/Digital+Items/2')
(['Other', 'Digital Items'], '/products/all/Digital+Items/3')
(['Other', 'Digital Items'], '/products/all/Digital+Items/4')
(['Other', 'Digital Items'], '/products/all/Digital+Items/5')
(['Other', 'Digital Items'], '/products/all/Digital+Items/6')
(['Other', 'Digital Items'], '/products/all/Digital+Items/7')
(['Other', 'Digital Items'], '/products/all/Digital+Items/8')
(['Other', 'Digital Items'], '/products/all/Digital+Items/9')
(['Other', 'Digital Items'], '/products/all/Digital+Items/10')
(['Other', 'Digital Items'], '/products/all/Digital+Items/11')
(['Other', 'Digital Items'], '/products/all/Digital+Items/12')
(['Other', 'Digital Items'], '/products/all/Digital+Items/13')
(['Other', 'Digital Items'], '/products/all/Digital+Items/14')
(['Other', 'Digital Items'], '/products/all/Digital+Items/15')
(['Other', 'Digital Items'], '/products/all/Digital+Items/16')
(['Other', 'Digital Items'], '/products/all/Digital+Items/17')
(['Other', 'Digital Items'], '/products/all/Digital+Items/18')
(['Other', 'Digital Items'], '/products/all/Digital+Items/19')
(['Other', 'Digital Items'], '/products/all/Digital+Items/20')
(['Other', 'Digital Items'], '/products/all/Digital+Items/21')
(['Other', 'Digital Items'], '/products/all/Digital+Items/22')
(['Other', 'Digital Items'], '/products/all/Digital+Items/23')
(['Other', 'Digital Items'], '/products/all/Digital+Items/24')
(['Other', 'Digital Items'], '/products/all/Digital+Items/25')
(['Other', 'Digital Items'], '/products/all/Digital+Items/26')
(['Other', 'Digital Items'], '/products/all/Digital+Items/27')
(['Other', 'Digital Items'], '/products/all/Digital+Items/28')
(['Other', 'Digital Items'], '/products/all/Digital+Items/29')
(['Other', 'Digital Items'], '/products/all/Digital+Items/30')
(['Other', 'Digital Items'], '/products/all/Digital+Items/31')
(['Other', 'Digital Items'], '/products/all/Digital+Items/32')
(['Other', 'Digital Items'], '/products/all/Digital+Items/33')
(['Other', 'Digital Items'], '/products/all/Digital+Items/34')
(['Other', 'Digital Items'], '/products/all/Digital+Items/35')
(['Other', 'Digital Items'], '/products/all/Digital+Items/36')
(['Other', 'Digital Items'], '/products/all/Digital+Items/37')
(['Other', 'Digital Items'], '/products/all/Digital+Items/38')
(['Other', 'Digital Items'], '/products/all/Digital+Items/39')
(['Other', 'Digital Items'], '/products/all/Digital+Items/40')
(['Other', 'Digital Items'], '/products/all/Digital+Items/41')
(['Other', 'Digital Items'], '/products/all/Digital+Items/42')
(['Other', 'Digital Items'], '/products/all/Digital+Items/43')
(['Other', 'Digital Items'], '/products/all/Digital+Items/44')
(['Other', 'Digital Items'], '/products/all/Digital+Items/45')
(['Other', 'Digital Items'], '/products/all/Digital+Items/46')
(['Other', 'Digital Items'], '/products/all/Digital+Items/47')
(['Other', 'Digital Items'], '/products/all/Digital+Items/48')
(['Other', 'Digital Items'], '/products/all/Digital+Items/49')
(['Other', 'Digital Items'], '/products/all/Digital+Items/50')
(['Other', 'Digital Items'], '/products/all/Digital+Items/51')
(['Other', 'Digital Items'], '/products/all/Digital+Items/52')
(['Other', 'Digital Items'], '/products/all/Digital+Items/53')
(['Other', 'Digital Items'], '/products/all/Digital+Items/54')
(['Other', 'Digital Items'], '/products/all/Digital+Items/55')
(['Other', 'Digital Items'], '/products/all/Digital+Items/56')
(['Other', 'Digital Items'], '/products/all/Digital+Items/57')
(['Other', 'Digital Items'], '/products/all/Digital+Items/58')
(['Other', 'Digital Items'], '/products/all/Digital+Items/59')
(['Other', 'Digital Items'], '/products/all/Digital+Items/60')
(['Other', 'Digital Items'], '/products/all/Digital+Items/61')
(['Other', 'Digital Items'], '/products/all/Digital+Items/62')
(['Other', 'Digital Items'], '/products/all/Digital+Items/63')
(['Other', 'Digital Items'], '/products/all/Digital+Items/64')
(['Other', 'Digital Items'], '/products/all/Digital+Items/65')
(['Other', 'Digital Items'], '/products/all/Digital+Items/66')
(['Other', 'Digital Items'], '/products/all/Digital+Items/67')
(['Other', 'Digital Items'], '/products/all/Digital+Items/68')
(['Other', 'Digital Items'], '/products/all/Digital+Items/69')
(['Other', 'Digital Items'], '/products/all/Digital+Items/70')
(['Other', 'Digital Items'], '/products/all/Digital+Items/71')
(['Other', 'Digital Items'], '/products/all/Digital+Items/72')
(['Other', 'Digital Items'], '/products/all/Digital+Items/73')
(['Other', 'Digital Items'], '/products/all/Digital+Items/74')
(['Other', 'Digital Items'], '/products/all/Digital+Items/75')
(['Other', 'Digital Items'], '/products/all/Digital+Items/76')
(['Other', 'Digital Items'], '/products/all/Digital+Items/77')
(['Other', 'Digital Items'], '/products/all/Digital+Items/78')
(['Other', 'Digital Items'], '/products/all/Digital+Items/79')
(['Other', 'Digital Items'], '/products/all/Digital+Items/80')
(['Other', 'Digital Items'], '/products/all/Digital+Items/81')
(['Other', 'Digital Items'], '/products/all/Digital+Items/82')
(['Other', 'Digital Items'], '/products/all/Digital+Items/83')
(['Other', 'Digital Items'], '/products/all/Digital+Items/84')
(['Other', 'Digital Items'], '/products/all/Digital+Items/85')
(['Other', 'Digital Items'], '/products/all/Digital+Items/86')
(['Other', 'Digital Items'], '/products/all/Digital+Items/87')
(['Other', 'Digital Items'], '/products/all/Digital+Items/88')
(['Other', 'Digital Items'], '/products/all/Digital+Items/89')
(['Other', 'Digital Items'], '/products/all/Digital+Items/90')
(['Other', 'Digital Items'], '/products/all/Digital+Items/91')
(['Other', 'Digital Items'], '/products/all/Digital+Items/92')
(['Other', 'Digital Items'], '/products/all/Digital+Items/93')
(['Other', 'Digital Items'], '/products/all/Digital+Items/94')
(['Other', 'Digital Items'], '/products/all/Digital+Items/95')
(['Other', 'Digital Items'], '/products/all/Digital+Items/96')
(['Other', 'Digital Items'], '/products/all/Digital+Items/97')
(['Other', 'Digital Items'], '/products/all/Digital+Items/98')
(['Other', 'Digital Items'], '/products/all/Digital+Items/99')
(['Other', 'Digital Items'], '/products/all/Digital+Items/100')
(['Other', 'Digital Items'], '/products/all/Digital+Items/101')
(['Other', 'Digital Items'], '/products/all/Digital+Items/102')
(['Other', 'Digital Items'], '/products/all/Digital+Items/103')
(['Other', 'Digital Items'], '/products/all/Digital+Items/104')
(['Other', 'Digital Items'], '/products/all/Digital+Items/105')
(['Other', 'Digital Items'], '/products/all/Digital+Items/106')
(['Other', 'Digital Items'], '/products/all/Digital+Items/107')
(['Other', 'Digital Items'], '/products/all/Digital+Items/108')
(['Other', 'Digital Items'], '/products/all/Digital+Items/109')
(['Other', 'Digital Items'], '/products/all/Digital+Items/110')
(['Other', 'Digital Items'], '/products/all/Digital+Items/111')
(['Other', 'Digital Items'], '/products/all/Digital+Items/112')
(['Other', 'Digital Items'], '/products/all/Digital+Items/113')
(['Other', 'Digital Items'], '/products/all/Digital+Items/114')
(['Other', 'Digital Items'], '/products/all/Digital+Items/115')
(['Other', 'Digital Items'], '/products/all/Digital+Items/116')
(['Other', 'Digital Items'], '/products/all/Digital+Items/117')
[['Other', 'Other Items'], '/products/all/Other+Items']
(['Other', 'Other Items'], '/products/all/Other+Items/2')
(['Other', 'Other Items'], '/products/all/Other+Items/3')
(['Other', 'Other Items'], '/products/all/Other+Items/4')
(['Other', 'Other Items'], '/products/all/Other+Items/5')
(['Other', 'Other Items'], '/products/all/Other+Items/6')
(['Other', 'Other Items'], '/products/all/Other+Items/7')
(['Other', 'Other Items'], '/products/all/Other+Items/8')
(['Other', 'Other Items'], '/products/all/Other+Items/9')
(['Other', 'Other Items'], '/products/all/Other+Items/10')
(['Other', 'Other Items'], '/products/all/Other+Items/11')
(['Other', 'Other Items'], '/products/all/Other+Items/12')
(['Other', 'Other Items'], '/products/all/Other+Items/13')
(['Other', 'Other Items'], '/products/all/Other+Items/14')
(['Other', 'Other Items'], '/products/all/Other+Items/15')
(['Other', 'Other Items'], '/products/all/Other+Items/16')
(['Other', 'Other Items'], '/products/all/Other+Items/17')
(['Other', 'Other Items'], '/products/all/Other+Items/18')
(['Other', 'Other Items'], '/products/all/Other+Items/19')
(['Other', 'Other Items'], '/products/all/Other+Items/20')
(['Other', 'Other Items'], '/products/all/Other+Items/21')
(['Other', 'Other Items'], '/products/all/Other+Items/22')
(['Other', 'Other Items'], '/products/all/Other+Items/23')
(['Other', 'Other Items'], '/products/all/Other+Items/24')
(['Other', 'Other Items'], '/products/all/Other+Items/25')
(['Other', 'Other Items'], '/products/all/Other+Items/26')
(['Other', 'Other Items'], '/products/all/Other+Items/27')
(['Other', 'Other Items'], '/products/all/Other+Items/28')
(['Other', 'Other Items'], '/products/all/Other+Items/29')
(['Other', 'Other Items'], '/products/all/Other+Items/30')
[['Fraud', 'Credit Cards'], '/products/all/Credit+Cards']
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/2')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/3')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/4')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/5')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/6')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/7')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/8')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/9')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/10')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/11')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/12')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/13')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/14')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/15')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/16')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/17')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/18')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/19')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/20')
(['Fraud', 'Credit Cards'], '/products/all/Credit+Cards/21')
[['Fraud', 'Fullz'], '/products/all/Fullz']
(['Fraud', 'Fullz'], '/products/all/Fullz/2')
(['Fraud', 'Fullz'], '/products/all/Fullz/3')
(['Fraud', 'Fullz'], '/products/all/Fullz/4')
(['Fraud', 'Fullz'], '/products/all/Fullz/5')
(['Fraud', 'Fullz'], '/products/all/Fullz/6')
(['Fraud', 'Fullz'], '/products/all/Fullz/7')
(['Fraud', 'Fullz'], '/products/all/Fullz/8')
[['Fraud', 'Accounts'], '/products/all/Accounts']
(['Fraud', 'Accounts'], '/products/all/Accounts/2')
(['Fraud', 'Accounts'], '/products/all/Accounts/3')
(['Fraud', 'Accounts'], '/products/all/Accounts/4')
(['Fraud', 'Accounts'], '/products/all/Accounts/5')
(['Fraud', 'Accounts'], '/products/all/Accounts/6')
(['Fraud', 'Accounts'], '/products/all/Accounts/7')
(['Fraud', 'Accounts'], '/products/all/Accounts/8')
(['Fraud', 'Accounts'], '/products/all/Accounts/9')
(['Fraud', 'Accounts'], '/products/all/Accounts/10')
(['Fraud', 'Accounts'], '/products/all/Accounts/11')
(['Fraud', 'Accounts'], '/products/all/Accounts/12')
(['Fraud', 'Accounts'], '/products/all/Accounts/13')
(['Fraud', 'Accounts'], '/products/all/Accounts/14')
(['Fraud', 'Accounts'], '/products/all/Accounts/15')
(['Fraud', 'Accounts'], '/products/all/Accounts/16')
(['Fraud', 'Accounts'], '/products/all/Accounts/17')
(['Fraud', 'Accounts'], '/products/all/Accounts/18')
(['Fraud', 'Accounts'], '/products/all/Accounts/19')
(['Fraud', 'Accounts'], '/products/all/Accounts/20')
(['Fraud', 'Accounts'], '/products/all/Accounts/21')
(['Fraud', 'Accounts'], '/products/all/Accounts/22')
(['Fraud', 'Accounts'], '/products/all/Accounts/23')
(['Fraud', 'Accounts'], '/products/all/Accounts/24')
(['Fraud', 'Accounts'], '/products/all/Accounts/25')
(['Fraud', 'Accounts'], '/products/all/Accounts/26')
(['Fraud', 'Accounts'], '/products/all/Accounts/27')
(['Fraud', 'Accounts'], '/products/all/Accounts/28')
[['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related']
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/2')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/3')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/4')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/5')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/6')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/7')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/8')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/9')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/10')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/11')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/12')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/13')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/14')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/15')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/16')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/17')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/18')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/19')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/20')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/21')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/22')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/23')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/24')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/25')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/26')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/27')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/28')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/29')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/30')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/31')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/32')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/33')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/34')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/35')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/36')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/37')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/38')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/39')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/40')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/41')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/42')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/43')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/44')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/45')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/46')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/47')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/48')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/49')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/50')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/51')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/52')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/53')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/54')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/55')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/56')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/57')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/58')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/59')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/60')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/61')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/62')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/63')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/64')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/65')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/66')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/67')
(['Fraud', 'Other Fraud Related'], '/products/all/Other+Fraud+Related/68')
[['Fraud', 'Fake IDs'], '/products/all/Fake+IDs']
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/2')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/3')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/4')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/5')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/6')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/7')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/8')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/9')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/10')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/11')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/12')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/13')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/14')
(['Fraud', 'Fake IDs'], '/products/all/Fake+IDs/15')