TASK_LIST = [

((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD/8'),
((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/26'),
((('Narcotics', None, None, 0), ('Heroin', None, 'Narcotics', 1)), '/products/all/Heroin/14'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/24'),
((('Pharma', None, None, 0), ('Pain Medication', None, 'Pharma', 1)), '/products/all/Pain+Medication/4'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine/9'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building'),
((('Fraud', None, None, 0), ('Fullz', None, 'Fraud', 1)), '/products/all/Fullz/3'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine/25'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/12'),
((('Pharma', None, None, 0), ('ED Sex Meds', None, 'Pharma', 1)), '/products/all/ED+Sex+Meds/10'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/49'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/66'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/2'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/24'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/19'),
((('Fraud', None, None, 0), ('Fake IDs', None, 'Fraud', 1)), '/products/all/Fake+IDs'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/8'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/40'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/14'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/31'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/9'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/99'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/28'),
((('Pharma', None, None, 0), ('Other Pharma', None, 'Pharma', 1)), '/products/all/Other+Pharma'),
((('Cannabis', None, None, 0), ('Hashish', None, 'Cannabis', 1)), '/products/all/Hashish/4'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/8'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/17'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/8'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/14'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/70'),
((('Pharma', None, None, 0), ('Sedatives', None, 'Pharma', 1)), '/products/all/Sedatives'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/75'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/31'),
((('Pharma', None, None, 0), ('Other Pharma', None, 'Pharma', 1)), '/products/all/Other+Pharma/5'),
((('Pharma', None, None, 0), ('Pain Medication', None, 'Pharma', 1)), '/products/all/Pain+Medication'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/9'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/18'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/70'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/96'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/10'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/26'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/58'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/7'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/17'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/36'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/8'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/41'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/28'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/21'),
((('Stimulants', None, None, 0), ('2-FMA 4-FA', None, 'Stimulants', 1)), '/products/all/2%2DFMA+4%2DFA'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/10'),
((('Psychedelics', None, None, 0), ('2C-x', None, 'Psychedelics', 1)), '/products/all/2C%2Dx/2'),
((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD/7'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/54'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/22'),
((('Narcotics', None, None, 0), ('Heroin', None, 'Narcotics', 1)), '/products/all/Heroin/4'),
((('Narcotics', None, None, 0), ('Opium', None, 'Narcotics', 1)), '/products/all/Opium/3'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/24'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/12'),
((('Pharma', None, None, 0), ('ED Sex Meds', None, 'Pharma', 1)), '/products/all/ED+Sex+Meds/4'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/10'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/17'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/15'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/91'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/20'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/8'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/29'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/19'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/8'),
((('Psychedelics', None, None, 0), ('DMT AMT', None, 'Psychedelics', 1)), '/products/all/DMT+AMT/7'),
((('Stimulants', None, None, 0), ('Nicotine', None, 'Stimulants', 1)), '/products/all/Nicotine/3'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/19'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/22'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/65'),
((('Narcotics', None, None, 0), ('Heroin', None, 'Narcotics', 1)), '/products/all/Heroin'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/4'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/60'),
((('Stimulants', None, None, 0), ('Nicotine', None, 'Stimulants', 1)), '/products/all/Nicotine/4'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/76'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/62'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/87'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/23'),
((('Cannabis', None, None, 0), ('Edibles', None, 'Cannabis', 1)), '/products/all/Edibles/7'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/61'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/27'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/31'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/15'),
((('Pharma', None, None, 0), ('ED Sex Meds', None, 'Pharma', 1)), '/products/all/ED+Sex+Meds/2'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/90'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/47'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/20'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/18'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/116'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/71'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/15'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/110'),
((('Psychedelics', None, None, 0), ('DMT AMT', None, 'Psychedelics', 1)), '/products/all/DMT+AMT/2'),
((('Pharma', None, None, 0), ('Muscle Relaxers', None, 'Pharma', 1)), '/products/all/Muscle+Relaxers'),
((('Stimulants', None, None, 0), ('A-PVP', None, 'Stimulants', 1)), '/products/all/A%2DPVP'),
((('Pharma', None, None, 0), ('Other Pharma', None, 'Pharma', 1)), '/products/all/Other+Pharma/4'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/108'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/80'),
((('Narcotics', None, None, 0), ('Oxycodone', None, 'Narcotics', 1)), '/products/all/Oxycodone/5'),
((('Cannabis', None, None, 0), ('Hashish', None, 'Cannabis', 1)), '/products/all/Hashish/17'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/8'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/106'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/23'),
((('Narcotics', None, None, 0), ('Tramadol', None, 'Narcotics', 1)), '/products/all/Tramadol'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/85'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/26'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/12'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/4'),
((('Depressants', None, None, 0), ('GHB GBL', None, 'Depressants', 1)), '/products/all/GHB+GBL/5'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/16'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/40'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/22'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/54'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/3'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/43'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/30'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/14'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine/13'),
((('Cannabis', None, None, 0), ('Edibles', None, 'Cannabis', 1)), '/products/all/Edibles/3'),
((('Pharma', None, None, 0), ('Sedatives', None, 'Pharma', 1)), '/products/all/Sedatives/2'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/42'),
((('Narcotics', None, None, 0), ('Heroin', None, 'Narcotics', 1)), '/products/all/Heroin/10'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/5'),
((('Fraud', None, None, 0), ('Fullz', None, 'Fraud', 1)), '/products/all/Fullz/7'),
((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD/15'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/77'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/20'),
((('Narcotics', None, None, 0), ('Other Narcotics', None, 'Narcotics', 1)), '/products/all/Other+Narcotics'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/36'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/23'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/7'),
((('Other', None, None, 0), ('Drug Production', None, 'Other', 1)), '/products/all/Drug+Production'),
((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD/13'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/71'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/32'),
((('Dissociatives', None, None, 0), ('Salvia', None, 'Dissociatives', 1)), '/products/all/Salvia'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/11'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/18'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/33'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/103'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/18'),
((('Empathogens', None, None, 0), ('MDA MDAI', None, 'Empathogens', 1)), '/products/all/MDA+MDAI'),
((('Stimulants', None, None, 0), ('Methamphetamine', None, 'Stimulants', 1)), '/products/all/Methamphetamine'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/28'),
((('Depressants', None, None, 0), ('GHB GBL', None, 'Depressants', 1)), '/products/all/GHB+GBL/2'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/7'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/3'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/28'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/5'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/89'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/107'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/20'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/9'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/7'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate'),
((('Cannabis', None, None, 0), ('Edibles', None, 'Cannabis', 1)), '/products/all/Edibles/10'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/41'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/17'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/14'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/21'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/11'),
((('Pharma', None, None, 0), ('Other Pharma', None, 'Pharma', 1)), '/products/all/Other+Pharma/2'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/16'),
((('Psychedelics', None, None, 0), ('25x-NBOMe', None, 'Psychedelics', 1)), '/products/all/25x%2DNBOMe'),
((('Narcotics', None, None, 0), ('Tramadol', None, 'Narcotics', 1)), '/products/all/Tramadol/2'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/45'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/94'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/30'),
((('Cannabis', None, None, 0), ('Hashish', None, 'Cannabis', 1)), '/products/all/Hashish'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/10'),
((('Stimulants', None, None, 0), ('Methamphetamine', None, 'Stimulants', 1)), '/products/all/Methamphetamine/10'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/18'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/20'),
((('Psychedelics', None, None, 0), ('DMT AMT', None, 'Psychedelics', 1)), '/products/all/DMT+AMT/5'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/3'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/14'),
((('Narcotics', None, None, 0), ('Morphine', None, 'Narcotics', 1)), '/products/all/Morphine/2'),
((('Psychedelics', None, None, 0), ('5-MeO-MiPT', None, 'Psychedelics', 1)), '/products/all/5%2DMeO%2DMiPT'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/56'),
((('Psychedelics', None, None, 0), ('Mushrooms', None, 'Psychedelics', 1)), '/products/all/Mushrooms/3'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/59'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/71'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/11'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/100'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/61'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/6'),
((('Narcotics', None, None, 0), ('Other Narcotics', None, 'Narcotics', 1)), '/products/all/Other+Narcotics/4'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/23'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/15'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/4'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/27'),
((('Narcotics', None, None, 0), ('Tramadol', None, 'Narcotics', 1)), '/products/all/Tramadol/3'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/119'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/28'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/5'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/11'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/13'),
((('Psychedelics', None, None, 0), ('Mushrooms', None, 'Psychedelics', 1)), '/products/all/Mushrooms/4'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/19'),
((('Fraud', None, None, 0), ('Fake IDs', None, 'Fraud', 1)), '/products/all/Fake+IDs/10'),
((('Narcotics', None, None, 0), ('Buprenorphine', None, 'Narcotics', 1)), '/products/all/Buprenorphine'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/3'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/15'),
((('Psychedelics', None, None, 0), ('5-MeO-DiPT', None, 'Psychedelics', 1)), '/products/all/5%2DMeO%2DDiPT'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/20'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/95'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/2'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/46'),
((('Pharma', None, None, 0), ('Other Pharma', None, 'Pharma', 1)), '/products/all/Other+Pharma/10'),
((('Pharma', None, None, 0), ('Nootropics', None, 'Pharma', 1)), '/products/all/Nootropics/3'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine'),
((('Cannabis', None, None, 0), ('Hashish', None, 'Cannabis', 1)), '/products/all/Hashish/3'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/67'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine/33'),
((('Pharma', None, None, 0), ('ED Sex Meds', None, 'Pharma', 1)), '/products/all/ED+Sex+Meds'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/4'),
((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD/2'),
((('Pharma', None, None, 0), ('Sleep Aids', None, 'Pharma', 1)), '/products/all/Sleep+Aids/3'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine/35'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/21'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/39'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/18'),
((('Narcotics', None, None, 0), ('Heroin', None, 'Narcotics', 1)), '/products/all/Heroin/7'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/105'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/111'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/23'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/16'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/13'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/73'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/48'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/42'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/21'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/3'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/75'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/113'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/7'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/11'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/39'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/21'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/27'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/16'),
((('Fraud', None, None, 0), ('Fake IDs', None, 'Fraud', 1)), '/products/all/Fake+IDs/4'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/13'),
((('Cannabis', None, None, 0), ('Hashish', None, 'Cannabis', 1)), '/products/all/Hashish/2'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/17'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/9'),
((('Fraud', None, None, 0), ('Credit Cards', None, 'Fraud', 1)), '/products/all/Credit+Cards/18'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/15'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/24'),
((('Other', None, None, 0), ('Other Items', None, 'Other', 1)), '/products/all/Other+Items/2'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/56'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine/2'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/83'),
((('Narcotics', None, None, 0), ('Heroin', None, 'Narcotics', 1)), '/products/all/Heroin/3'),
((('Cannabis', None, None, 0), ('Concentrate', None, 'Cannabis', 1)), '/products/all/Concentrate/14'),
((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD/14'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/27'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/2'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/35'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/12'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/23'),
((('Pharma', None, None, 0), ('Pain Medication', None, 'Pharma', 1)), '/products/all/Pain+Medication/6'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/22'),
((('Empathogens', None, None, 0), ('MDMA', None, 'Empathogens', 1)), '/products/all/MDMA/4'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/8'),
((('Narcotics', None, None, 0), ('Other Narcotics', None, 'Narcotics', 1)), '/products/all/Other+Narcotics/3'),
((('Stimulants', None, None, 0), ('Methamphetamine', None, 'Stimulants', 1)), '/products/all/Methamphetamine/3'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/78'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/14'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/9'),
((('Stimulants', None, None, 0), ('Amphetamine', None, 'Stimulants', 1)), '/products/all/Amphetamine/5'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/20'),
((('Fraud', None, None, 0), ('Accounts', None, 'Fraud', 1)), '/products/all/Accounts/4'),
((('Narcotics', None, None, 0), ('Codeine', None, 'Narcotics', 1)), '/products/all/Codeine/2'),
((('Other', None, None, 0), ('Body Building', None, 'Other', 1)), '/products/all/Body+Building/11'),
((('Empathogens', None, None, 0), ('Ecstacy', None, 'Empathogens', 1)), '/products/all/Ecstacy/8'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/21'),
((('Fraud', None, None, 0), ('Other Fraud Related', None, 'Fraud', 1)), '/products/all/Other+Fraud+Related/65'),
((('Cannabis', None, None, 0), ('Weed', None, 'Cannabis', 1)), '/products/all/Weed/110'),
((('Stimulants', None, None, 0), ('Methamphetamine', None, 'Stimulants', 1)), '/products/all/Methamphetamine/11'),
((('Dissociatives', None, None, 0), ('Ketamine', None, 'Dissociatives', 1)), '/products/all/Ketamine/3'),
((('Stimulants', None, None, 0), ('Cocaine', None, 'Stimulants', 1)), '/products/all/Cocaine/37'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/7'),
((('Pharma', None, None, 0), ('Benzos', None, 'Pharma', 1)), '/products/all/Benzos/16'),
((('Psychedelics', None, None, 0), ('LSD', None, 'Psychedelics', 1)), '/products/all/LSD/10'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/28'),
((('Cannabis', None, None, 0), ('Edibles', None, 'Cannabis', 1)), '/products/all/Edibles/6'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/68'),
((('Cannabis', None, None, 0), ('Synthetics', None, 'Cannabis', 1)), '/products/all/Synthetics/2'),
((('Other', None, None, 0), ('Drug Production', None, 'Other', 1)), '/products/all/Drug+Production/2'),
((('Other', None, None, 0), ('Digital Items', None, 'Other', 1)), '/products/all/Digital+Items/33')

]